# Generated by Django 5.0.6 on 2024-07-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('two_factor_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(db_collation='Latin1_General_CI_AS', null=True)),
                ('password', models.TextField(db_collation='Latin1_General_CI_AS', null=True)),
                ('email', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
                ('two_factor_secret', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', null=True)),
                ('failed_login_attempts', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('session_token', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', null=True)),
                ('last_check_token', models.DateTimeField(blank=True, null=True)),
                ('email_otp', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', null=True)),
                ('otp_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Authorization',
                'managed': False,
            },
        ),
    ]
