# Generated by Django 5.0.6 on 2024-08-29 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_secret', models.CharField(blank=True, max_length=100)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('last_failed_login_attempt', models.DateTimeField(blank=True, null=True)),
                ('session_token', models.CharField(blank=True, max_length=255)),
                ('last_check_token', models.DateTimeField(blank=True, null=True)),
                ('email_otp', models.CharField(blank=True, max_length=64, null=True)),
                ('otp_timestamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Authorization',
        ),
    ]
