# Generated by Django 5.0.3 on 2024-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0005_alter_backupcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='BackupCode',
        ),
    ]
