# Generated by Django 5.0.3 on 2024-03-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0006_userprofile_session_token_delete_backupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_otp',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
