# Generated by Django 5.0.6 on 2024-07-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0007_userprofile_email_otp_userprofile_otp_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_check_token',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
