# Generated by Django 5.0.6 on 2024-07-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0008_userprofile_last_check_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='session_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
